const en = {};
en.LEARN = "Learn";
en.ABOUT = "About";
en.GET_INVOLVED = "Get Involved";
en.OUR_STORY = "Our Story";
en.DASHBOARD = "Dashboard";
en.SWITCH_VIEWS = "Switch to %1 View";
en.SWITCH_TO_VIEW = "Switch to %1 View";
en.STUDENT = "Student";
en.VOLUNTEER = "Volunteer";
en.ADMIN = "Admin";
en.PARTNER = "Partner";
en.STUDENTS = "Students";
en.VOLUNTEERS = "Volunteers";
en.PARTNERS = "Partners";
en.DONATE = "Donate";
en.VOLUNTEER_WITH_US = "Volunteer with Us";
en.MERAKI_TEAM = "Meraki Team";
en.OPPORTUNITIES = "Opportunities";
en.CAREERS = "Careers";
en.PROFILE = "Profile";
en.LOGOUT = "Logout";

export default en;
