const hi = {};
hi.LEARN = "सीखें";
hi.ABOUT = "के बारे में";
hi.GET_INVOLVED = "उलझना";
hi.OUR_STORY = "हमारी कहानी";
hi.DASHBOARD = "डैशबोर्ड";
hi.SWITCH_VIEWS = "दृष्टिकोण स्विच करें";
hi.SWITCH_TO_VIEW = "%1 के दृष्टिकोण पर स्विच करें";
hi.STUDENT = "छात्र";
hi.VOLUNTEER = "स्वयंसेवक";
hi.ADMIN = "एडमिन";
hi.PARTNER = "साथी";
hi.STUDENTS = "छात्र";
hi.VOLUNTEERS = "स्वयंसेवक";
hi.PARTNERS = "साथी";
hi.DONATE = "दान करें";
hi.VOLUNTEER_WITH_US = "हमारे साथ स्वयंसेवक करें";
hi.MERAKI_TEAM = "मेराकी टीम";
hi.OPPORTUNITIES = "अवसर";
hi.CAREERS = "करियर";
hi.PROFILE = "प्रोफ़ाइल";
hi.LOGOUT = "लॉगआउट";

export default hi;
